# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|

	config.vm.define :server1 do |server1|
    		server1.vm.box = "bento/ubuntu-22.04"
    		server1.vm.network :private_network, ip: "192.168.50.3"
		server1.vm.network :public_network
    		server1.vm.hostname = "server1"
  	end
  	config.vm.define :server2 do |server2|
    		server2.vm.box = "bento/ubuntu-22.04"
    		server2.vm.network :private_network, ip: "192.168.50.2"
    		server2.vm.hostname = "server2"
  	end
end